export enum LANGUAGE {
	EN = 'EN',
	LV = 'LV',
	RU = 'RU',
}

export enum THEME {
	DARK = 'DARK',
	LIGHT = 'LIGHT',
}

export enum AUTHORIZATION_STATUS {
	REGISTRATION = 'REGISTRATION',
	SIGN_IN = 'SIGN_IN',
}

export enum ROLE_AUTHORIZED_USER {
	USER = 'USER',
	ADMIN = 'ADMIN',
	OTHER = 'OTHER',
}

export enum LABEL_TEST_TYPE {
	DEPRESSION = 'DEPRESSION',
	SHIZOPHRENIA = 'SHIZOPHRENIA',
	TREVOR = 'TREVOR',
	AUTISM = 'AUTISM',
	DEMENTIA = 'DEMENTIA',
	STRESS = 'STRESS',
}

export enum ROLE_AUTH_USER_PRIVILEGE {
	ALL = 'ALL',
	READ_ONLY = 'READ_ONLY',
	ADD_CONTENT = 'ADD_CONTENT',
	DELETE_CONTENT = 'DELETE_CONTENT',
	EDIT_CONTENT = 'EDIT_CONTENT',

}

export enum ARTICLE_TYPE {
	PREVIEW = 'PREVIEW',
	MEDIUM = 'MEDIUM',
	FULL = 'FULL',
}

export enum USER_FAVORITES_TYPE {
	ARTICLES = 'ARTICLES',
	TESTS = 'TESTS',
	NEWS = 'NEWS',
}

export enum TEST_TYPE {
	PREVIEW = 'PREVIEW',
	FULL = 'FULL',
}

export enum NEWS_TYPE {
	PREVIEW = 'PREVIEW',
	MEDIUM = 'MEDIUM',
	FULL = 'FULL',
}

export enum USER_FAVORITES_ACTION {
	ADD = 'ADD',
	REMOVE = 'REMOVE',
}

export enum UPDATE_USER_DATA_TYPE {
	NAME = 'NAME',
	PASSWORD = 'PASSWORD',
	FAVORITES = 'FAVORITES',
}

export enum APP_PATH_ROUTER {
	MAIN = '/',
	NEWS = '/news',
	TESTS = '/tests',
	ARTICLES = '/articles',
	CONSULTATION = '/consultation',
	USERS = '/user',
	AUTHORIZATION = '/authorization',
}
